package policy

var ValidEffects = map[string]map[string][]string{
    "host": {
        "anti_malware.crypto_miners": []string{"disable", "alert", "prevent"},
        "anti_malware.denied_processes.effect": []string{"alert", "prevent"},
        "anti_malware.encrypted_binaries": []string{"disable", "alert"},
        "anti_malware.execution_flow_hijacking": []string{"disable", "alert"},
        "anti_malware.malware_from_advanced_threat_protection": []string{"disable", "alert"},
        "anti_malware.malware_from_custom_feed": []string{"disable", "alert"},
        "anti_malware.non_packaged_binaries_service": []string{"disable", "alert", "prevent"},
        "anti_malware.non_packaged_binaries_user": []string{"disable", "alert", "prevent"},
        "anti_malware.processes_temporary_storage": []string{"disable", "alert", "prevent"},
        "anti_malware.reverse_shell": []string{"disable", "alert"},
        "anti_malware.suspicious_elf_headers": []string{"disable", "alert"},
        "anti_malware.web_shell": []string{"disable", "alert", "prevent"},
        "anti_malware.wild_fire_analysis": []string{"disable", "alert"},
        "networking.suspicious_ips_custom_feed": []string{"disable", "alert"},
        "networking.denied_ips_ports_effect": []string{"disable", "alert"},
        "networking.suspicious_ips_advanced_threat_protection_effect": []string{"disable", "alert"},
        "networking.denied_dns_domains_effect": []string{"disable", "alert", "prevent"},
        "networking.suspicious_domains_advanced_threat_protection_effect": []string{"disable", "alert", "prevent"},
        // TODO: custom rules
    },
    "container": {
        "anti_malware.malware_from_advanced_threat_protection": []string{"disable", "alert", "prevent", "block"},
        "anti_malware.kubernetes_attacks": []string{"disable", "alert", "prevent", "block"},
        "anti_malware.suspicious_cloud_provider_api_queries": []string{"disable", "alert", "prevent", "block"},
        "anti_malware.wild_fire_analysis": []string{"disable", "alert", "block"},
        "file_system.changes_to_binaries": []string{"disable", "alert", "prevent", "block"},
        "file_system.detection_of_encrypted_binaries": []string{"disable", "alert", "prevent", "block"},
        "file_system.changes_to_ssh_admin_account_config_files": []string{"disable", "alert", "prevent", "block"},
        "file_system.suspicious_elf_headers": []string{"disable", "alert", "prevent", "block"},
        "file_system.denied_paths_effect": []string{"disable", "alert", "prevent", "block"},
        "file_system.all_other_paths_effect": []string{"alert", "prevent", "block"},
        "processes.processes_from_modified_binaries": []string{"disable", "alert", "prevent", "block"},
        "processes.crypto_miners": []string{"disable", "alert", "prevent", "block"},
        "processes.reverse_shell": []string{"disable", "alert", "prevent", "block"},
        "processes.lateral_movement_processes": []string{"disable", "alert", "prevent", "block"},
        "processes.processes_started_with_suid": []string{"disable", "alert", "prevent", "block"},
        "processes.denied_processes.effect": []string{"disable", "alert", "prevent", "block"},
        "processes.all_other_processes_effect": []string{"disable", "alert", "prevent", "block"},
        "networking.network_activity_from_modified_binaries": []string{"disable", "alert", "block"},
        "networking.port_scanning": []string{"disable", "alert", "block"},
        "networking.raw_sockets": []string{"disable", "alert", "block"},
        "networking.denied_listening_ports_effect": []string{"disable", "alert", "block"},
        "networking.denied_outbound_internet_ports_effect": []string{"disable", "alert", "block"},
        "networking.denied_outbound_ips_effect": []string{"disable", "alert", "block"},
        "networking.all_other_activity_effect": []string{"alert", "block"},
        "networking.denied_dns_domains_effect": []string{"disable", "alert", "prevent", "block"},
        "networking.all_other_domains_effect": []string{"alert", "prevent", "block"},
    },
    "serverless": {
        "file_system.denied_paths_effect": []string{"alert", "prevent"},
        "processes.denied_processes_effect": []string{"alert", "prevent"},
        "networking.denied_ips_ports_effect": []string{"alert", "prevent"},
        "networking.denied_dns_domains_effect": []string{"alert", "prevent"},
    },
    "app_embedded": {
        "file_system.denied_paths_effect": []string{"alert", "prevent"},
        "file_system.wild_fire_analysis": []string{"disable", "alert"},
        "processes.denied_processes_effect": []string{"alert", "prevent"},
        "networking.denied_ips_ports_effect": []string{"alert", "prevent"},
        "networking.denied_dns_domains_effect": []string{"alert", "prevent"},
    },
}
