name: Test

on:
  push:
    branches: [ "github-actions", "migrate-to-plugin-framework" ]
  pull_request:
    branches: [ "github-actions", "migrate-to-plugin-framework" ]

env:
  CONFIG_DIRECTORY: "./"
  PRISMACLOUDCOMPUTE_CONSOLE_URL: "${{ secrets.PCC_CONSOLE_URL }}"
  PRISMACLOUDCOMPUTE_USERNAME: "${{ secrets.PCC_USERNAME }}"
  PRISMACLOUDCOMPUTE_PASSWORD: "${{ secrets.PCC_PASSWORD }}"

permissions:
  contents: read

jobs:
  acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get public IP
        id: ip
        uses: haythem/public-ip@v1.3
      - name: Update security group
        run: |
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws ec2 authorize-security-group-ingress --region ${{ secrets.AWS_REGION }} --group-id ${{ secrets.AWS_TEST_SG_ID }} --protocol tcp --port 8083 --cidr ${{ steps.ip.outputs.ipv4 }}/32
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -o terraform-provider-prismacloudcompute
      - run: go test -v ./internal/acceptance/...
        env:
          TF_ACC: '1'
      - name: Revoke security group ingress 
        run: |
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws ec2 revoke-security-group-ingress --region ${{ secrets.AWS_REGION }} --group-id ${{ secrets.AWS_TEST_SG_ID }} --protocol tcp --port 8083 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        if: always()
