name: Test

on:
  push:
    branches: [ "github-actions", "migrate-to-plugin-framework" ]
  pull_request:
    branches: [ "github-actions", "migrate-to-plugin-framework" ]

env:
  CONFIG_DIRECTORY: "./"
  PRISMACLOUDCOMPUTE_CONSOLE_URL: "${{ secrets.PCC_CONSOLE_URL }}"
  PRISMACLOUDCOMPUTE_USERNAME: "${{ secrets.PCC_USERNAME }}"
  PRISMACLOUDCOMPUTE_PASSWORD: "${{ secrets.PCC_ADMIN_PASSWORD }}"

permissions:
  contents: read

jobs:
  acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -o terraform-provider-prismacloudcompute
      - run: go test -v ./internal/acceptance/...
        env:
          TF_ACC: '1'
